root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/superplane cmd/server/main.go"
bin = "tmp/superplane"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["web_src", "tmp", "build", "api/swagger", "node_modules"]
stop_on_error = true
send_interrupt = true
kill_delay = "3s"

[log]
time = true

[misc]
clean_on_exit = true
