apiVersion: v2
name: superplane-chart
description: A Helm chart for the SuperPlane application
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
  - name: cert-manager
    version: "1.13.3"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
